apiVersion: v1
kind: Service
metadata:
  name: errorlens-backend
  namespace: errorlens-stage
spec:
  type: NodePort
  selector:
    app: errorlens-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31200
    protocol: TCP
