apiVersion: v1
kind: Service
metadata:
  name: errorlens-frontend
  namespace: errorlens-stage
spec:
  type: NodePort
  selector:
    app: errorlens-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31201
    protocol: TCP
