"""
Export Service - Handles session export to various formats.

Supported formats: markdown, postman, pytest, restassured, testit
"""

import io
import json
import zipfile
from typing import Optional

from app.models.db_models import Session
from app.models_pydantic import (
    ExportPostmanRequest,
    RecordedRequest,
    RecordedHttpExchange,
)
from app.generators import (
    generate_postman_collection,
    generate_pytest_file,
    generate_restassured_file,
    generate_pom_xml,
    generate_testit_testcase,
)


class ExportService:
    """Service for exporting sessions to various formats."""

    def export_markdown(self, session: Session) -> str:
        """Export session as markdown report."""
        lines = [
            "# ErrorLens Report",
            "",
            f"**URL:** {session.url}",
            f"**Date:** {session.created_at.isoformat()}",
            f"**Duration:** {session.recording_duration_ms}ms",
            "",
        ]

        if session.analysis:
            lines.extend([
                "## Analysis",
                "",
                f"**Severity:** {session.analysis.severity.upper()}",
                "",
                "### Summary",
                f"{session.analysis.summary}",
                "",
                "### Probable Cause",
                f"{session.analysis.probable_cause}",
                "",
                "### Suggested Fix",
                f"{session.analysis.suggested_fix}",
                "",
            ])
            if session.analysis.details:
                lines.extend([
                    "### Details",
                    "```",
                    f"{session.analysis.details}",
                    "```",
                    "",
                ])

        if session.data:
            if session.data.console_logs:
                lines.extend([
                    f"## Console Logs ({len(session.data.console_logs)})",
                    "",
                ])
                for log in session.data.console_logs[:10]:
                    lines.append(f"- [{log.get('level', 'log')}] {log.get('message', '')[:100]}")
                if len(session.data.console_logs) > 10:
                    lines.append(f"- ... and {len(session.data.console_logs) - 10} more")
                lines.append("")

            if session.data.network_errors:
                lines.extend([
                    f"## Network Errors ({len(session.data.network_errors)})",
                    "",
                ])
                for err in session.data.network_errors[:5]:
                    lines.append(f"- {err.get('method', 'GET')} {err.get('url', '')[:80]} → {err.get('status', '?')}")
                lines.append("")

        lines.extend([
            "---",
            "*Generated by ErrorLens*",
        ])

        return "\n".join(lines)

    def export_postman(self, session: Session) -> dict:
        """Export session as Postman collection."""
        if not session.data or not session.data.recorded_requests:
            raise ValueError("No recorded requests to export")

        request = ExportPostmanRequest(
            recorded_requests=[
                RecordedRequest(**req) for req in session.data.recorded_requests
            ],
            collection_name=f"ErrorLens - {session.url[:50]}",
            base_url_variable=True,
            generate_tests=True,
        )
        result = generate_postman_collection(request)
        return result.collection

    def export_pytest(self, session: Session) -> str:
        """Export session as pytest test file."""
        if not session.data or not session.data.recorded_requests:
            raise ValueError("No recorded requests to export")

        exchanges = [
            RecordedHttpExchange(**req) for req in session.data.recorded_requests
        ]

        return generate_pytest_file(
            recorded_requests=exchanges,
            test_name=f"test_session_{session.id[:8]}",
        )

    def export_restassured(self, session: Session) -> bytes:
        """Export session as REST Assured project (ZIP)."""
        if not session.data or not session.data.recorded_requests:
            raise ValueError("No recorded requests to export")

        exchanges = [
            RecordedHttpExchange(**req) for req in session.data.recorded_requests
        ]

        class_name = f"Session{session.id[:8].replace('-', '').upper()}Test"
        java_code = generate_restassured_file(exchanges, class_name=class_name)

        # Create ZIP
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
            package_path = "com/errorlens/tests"
            zf.writestr(f"src/test/java/{package_path}/{class_name}.java", java_code)
            zf.writestr("pom.xml", generate_pom_xml())
            zf.writestr("README.md", "# Run: mvn test")

        zip_buffer.seek(0)
        return zip_buffer.getvalue()

    def export_testit(
        self,
        session: Session,
        subformat: str = "json",
    ) -> str:
        """Export session as Test IT testcase."""
        session_data = {
            "id": session.id,
            "url": session.url,
            "recorded_requests": session.data.recorded_requests if session.data else [],
            "has_errors": bool(session.data and session.data.network_errors),
        }

        analysis = None
        if session.analysis:
            analysis = {
                "summary": session.analysis.summary,
                "probable_cause": session.analysis.probable_cause,
                "severity": session.analysis.severity,
            }

        return generate_testit_testcase(session_data, analysis, subformat)

    def get_content_type(self, format: str, subformat: str = "json") -> str:
        """Get content type for export format."""
        content_types = {
            "markdown": "text/markdown",
            "postman": "application/json",
            "pytest": "text/x-python",
            "restassured": "application/zip",
            "testit": {
                "json": "application/json",
                "xml": "application/xml",
                "markdown": "text/markdown",
            },
        }

        if format == "testit":
            return content_types["testit"].get(subformat, "application/json")
        return content_types.get(format, "application/octet-stream")

    def get_filename(self, session_id: str, format: str, subformat: str = "json") -> str:
        """Get filename for export."""
        short_id = session_id[:8]
        filenames = {
            "markdown": f"errorlens-{short_id}.md",
            "postman": f"errorlens-{short_id}.postman_collection.json",
            "pytest": f"test_session_{short_id}.py",
            "restassured": f"Session{short_id.replace('-', '').upper()}Test.zip",
            "testit": {
                "json": f"testcase-{short_id}.json",
                "xml": f"testcase-{short_id}.xml",
                "markdown": f"testcase-{short_id}.md",
            },
        }

        if format == "testit":
            return filenames["testit"].get(subformat, f"testcase-{short_id}.json")
        return filenames.get(format, f"export-{short_id}")
