"""Constants for demo seed data — test cases, tasks, folders."""

# Demo test cases - разные типы для демонстрации
DEMO_TEST_CASES = [
    {
        "title": "Авторизация: успешный вход с корректными данными",
        "description": "Проверка входа пользователя с валидными учетными данными",
        "preconditions": "Пользователь зарегистрирован в системе",
        "postconditions": "Пользователь авторизован, отображается главная страница",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Авторизация",
        "tags": ["smoke", "auth", "positive"],
        "steps": [
            {"step": 1, "action": "Открыть страницу логина", "expected": "Отображается форма входа"},
            {"step": 2, "action": "Ввести корректный email", "expected": "Email введен"},
            {"step": 3, "action": "Ввести корректный пароль", "expected": "Пароль введен"},
            {"step": 4, "action": "Нажать кнопку 'Войти'", "expected": "Пользователь перенаправлен на главную"},
        ],
    },
    {
        "title": "Авторизация: вход с неверным паролем",
        "description": "Проверка отображения ошибки при неверном пароле",
        "preconditions": "Пользователь зарегистрирован",
        "postconditions": "Отображается сообщение об ошибке",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Авторизация",
        "tags": ["auth", "negative"],
        "steps": [
            {"step": 1, "action": "Открыть страницу логина", "expected": "Форма входа отображается"},
            {"step": 2, "action": "Ввести корректный email", "expected": "Email введен"},
            {"step": 3, "action": "Ввести неверный пароль", "expected": "Пароль введен"},
            {"step": 4, "action": "Нажать 'Войти'", "expected": "Сообщение 'Неверный пароль'"},
        ],
    },
    {
        "title": "Регистрация: создание нового аккаунта",
        "description": "Проверка регистрации нового пользователя",
        "preconditions": "Email не используется в системе",
        "postconditions": "Создан новый аккаунт, отправлено письмо подтверждения",
        "priority": "Critical",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "Регистрация",
        "tags": ["registration", "smoke", "positive"],
        "steps": [
            {"step": 1, "action": "Открыть страницу регистрации", "expected": "Форма регистрации"},
            {"step": 2, "action": "Заполнить все обязательные поля", "expected": "Поля заполнены"},
            {"step": 3, "action": "Принять пользовательское соглашение", "expected": "Чекбокс отмечен"},
            {"step": 4, "action": "Нажать 'Зарегистрироваться'", "expected": "Аккаунт создан"},
        ],
    },
    {
        "title": "API: GET /sessions возвращает список сессий",
        "description": "Проверка получения списка сессий через API",
        "preconditions": "Авторизованный запрос с JWT токеном",
        "postconditions": "Возвращен JSON со списком сессий",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "API",
        "tags": ["api", "sessions", "positive"],
        "steps": [
            {"step": 1, "action": "Отправить GET /sessions", "expected": "Status 200"},
            {"step": 2, "action": "Проверить структуру ответа", "expected": "Массив объектов"},
            {"step": 3, "action": "Проверить поля сессии", "expected": "id, url, created_at присутствуют"},
        ],
    },
    {
        "title": "API: POST /sessions создает новую сессию",
        "description": "Проверка создания сессии записи ошибок",
        "preconditions": "Валидный JWT токен",
        "postconditions": "Сессия создана в БД",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "API",
        "tags": ["api", "sessions", "positive"],
        "steps": [
            {"step": 1, "action": "POST /sessions с данными", "expected": "Status 201"},
            {"step": 2, "action": "Проверить id в ответе", "expected": "UUID формат"},
            {"step": 3, "action": "GET созданную сессию", "expected": "Данные совпадают"},
        ],
    },
    {
        "title": "UI: Дашборд отображает статистику",
        "description": "Проверка корректного отображения дашборда",
        "preconditions": "Пользователь авторизован",
        "postconditions": "Статистика отображается корректно",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "UI",
        "tags": ["ui", "dashboard", "smoke"],
        "steps": [
            {"step": 1, "action": "Открыть дашборд", "expected": "Страница загружена"},
            {"step": 2, "action": "Проверить счетчик сессий", "expected": "Число >= 0"},
            {"step": 3, "action": "Проверить график", "expected": "График отображается"},
        ],
    },
    {
        "title": "Экспорт: генерация Postman коллекции",
        "description": "Проверка экспорта сессии в Postman формат",
        "preconditions": "Сессия с записанными запросами",
        "postconditions": "Скачан .json файл Postman коллекции",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "Экспорт",
        "tags": ["export", "postman", "integration"],
        "steps": [
            {"step": 1, "action": "Открыть детали сессии", "expected": "Сессия открыта"},
            {"step": 2, "action": "Нажать 'Export Postman'", "expected": "Кнопка активна"},
            {"step": 3, "action": "Проверить скачанный файл", "expected": "Валидный JSON"},
        ],
    },
    {
        "title": "Экспорт: генерация pytest тестов",
        "description": "Проверка генерации Python тестов",
        "preconditions": "Сессия с HTTP запросами",
        "postconditions": "Скачан .py файл с тестами",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Экспорт",
        "tags": ["export", "pytest", "code-gen"],
        "steps": [
            {"step": 1, "action": "Выбрать сессию", "expected": "Сессия выбрана"},
            {"step": 2, "action": "Нажать 'Generate pytest'", "expected": "Генерация запущена"},
            {"step": 3, "action": "Скачать файл", "expected": "test_*.py файл"},
            {"step": 4, "action": "Проверить синтаксис", "expected": "Python валиден"},
        ],
    },
    {
        "title": "AI Анализ: определение severity ошибки",
        "description": "Проверка AI анализа тяжести ошибок",
        "preconditions": "Сессия с JS ошибками",
        "postconditions": "severity определен корректно",
        "priority": "Low",
        "status": "Draft",
        "automation_status": "Manual",
        "folder": "AI",
        "tags": ["ai", "analysis", "severity"],
        "steps": [
            {"step": 1, "action": "Записать сессию с ошибкой", "expected": "Ошибка записана"},
            {"step": 2, "action": "Запустить AI анализ", "expected": "Анализ выполнен"},
            {"step": 3, "action": "Проверить severity", "expected": "low/medium/high/critical"},
        ],
    },
    {
        "title": "Безопасность: XSS в поле поиска",
        "description": "Проверка защиты от XSS атак",
        "preconditions": "Авторизованный пользователь",
        "postconditions": "Скрипт не выполняется",
        "priority": "Critical",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Security",
        "tags": ["security", "xss", "negative"],
        "steps": [
            {"step": 1, "action": "Ввести <script>alert(1)</script>", "expected": "Текст экранирован"},
            {"step": 2, "action": "Проверить DOM", "expected": "Нет script тега"},
            {"step": 3, "action": "Проверить Network", "expected": "Нет XHR с payload"},
        ],
    },
    {
        "title": "API: DELETE /sessions удаляет сессию",
        "description": "Проверка удаления сессии через API",
        "preconditions": "Существует сессия, авторизованный запрос",
        "postconditions": "Сессия удалена из БД",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "API",
        "tags": ["api", "sessions", "delete"],
        "steps": [
            {"step": 1, "action": "DELETE /sessions/{id}", "expected": "Status 200"},
            {"step": 2, "action": "GET /sessions/{id}", "expected": "Status 404"},
        ],
    },
    {
        "title": "API: GET /testcases возвращает пагинированный список",
        "description": "Проверка пагинации списка тест-кейсов",
        "preconditions": "Существует >10 тест-кейсов",
        "postconditions": "Возвращен пагинированный список",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "API",
        "tags": ["api", "testcases", "pagination"],
        "steps": [
            {"step": 1, "action": "GET /testcases?limit=5", "expected": "5 элементов в ответе"},
            {"step": 2, "action": "Проверить total count", "expected": "total > 5"},
            {"step": 3, "action": "GET /testcases?offset=5&limit=5", "expected": "Следующая страница"},
        ],
    },
    {
        "title": "UI: Список тест-кейсов сортируется по приоритету",
        "description": "Проверка сортировки тест-кейсов в UI",
        "preconditions": "Есть тест-кейсы разных приоритетов",
        "postconditions": "Тест-кейсы отсортированы",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "UI",
        "tags": ["ui", "testcases", "sorting"],
        "steps": [
            {"step": 1, "action": "Открыть список тест-кейсов", "expected": "Список загружен"},
            {"step": 2, "action": "Нажать сортировку по приоритету", "expected": "Critical первыми"},
            {"step": 3, "action": "Проверить порядок", "expected": "Critical > High > Medium > Low"},
        ],
    },
    {
        "title": "UI: Модальное окно сессии показывает stacktrace",
        "description": "Проверка отображения stacktrace в деталях сессии",
        "preconditions": "Сессия с JS ошибкой и stacktrace",
        "postconditions": "Stacktrace отображается форматированно",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "UI",
        "tags": ["ui", "sessions", "stacktrace"],
        "steps": [
            {"step": 1, "action": "Открыть сессию с ошибкой", "expected": "Детали сессии"},
            {"step": 2, "action": "Найти секцию stacktrace", "expected": "Stacktrace виден"},
            {"step": 3, "action": "Проверить форматирование", "expected": "Моноширинный шрифт, подсветка"},
        ],
    },
    {
        "title": "Security: CSRF токен проверяется на мутирующих запросах",
        "description": "Проверка защиты от CSRF атак",
        "preconditions": "Авторизованный пользователь",
        "postconditions": "Запрос без CSRF токена отклонён",
        "priority": "Critical",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Security",
        "tags": ["security", "csrf", "negative"],
        "steps": [
            {"step": 1, "action": "POST без CSRF токена", "expected": "Status 403"},
            {"step": 2, "action": "POST с валидным CSRF", "expected": "Status 200"},
        ],
    },
    {
        "title": "Security: SQL injection в параметрах фильтрации",
        "description": "Проверка защиты от SQL injection",
        "preconditions": "Авторизованный пользователь",
        "postconditions": "SQL injection не выполняется",
        "priority": "Critical",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Security",
        "tags": ["security", "sql-injection", "negative"],
        "steps": [
            {"step": 1, "action": "GET /sessions?search=' OR 1=1--", "expected": "Пустой результат или 400"},
            {"step": 2, "action": "Проверить логи БД", "expected": "Параметризованный запрос"},
        ],
    },
    {
        "title": "Авторизация: Refresh token ротация при истечении access token",
        "description": "Проверка автоматического обновления токенов",
        "preconditions": "Access token истёк, refresh token валиден",
        "postconditions": "Выдан новый access token",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Авторизация",
        "tags": ["auth", "jwt", "refresh"],
        "steps": [
            {"step": 1, "action": "Дождаться истечения access token", "expected": "401 на запрос"},
            {"step": 2, "action": "POST /auth/refresh с refresh token", "expected": "Новый access token"},
            {"step": 3, "action": "Повторить запрос с новым token", "expected": "Status 200"},
        ],
    },
    {
        "title": "Авторизация: Logout инвалидирует refresh token",
        "description": "Проверка инвалидации токена при выходе",
        "preconditions": "Пользователь авторизован",
        "postconditions": "Refresh token больше не работает",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Авторизация",
        "tags": ["auth", "logout", "negative"],
        "steps": [
            {"step": 1, "action": "POST /auth/logout", "expected": "Status 200"},
            {"step": 2, "action": "POST /auth/refresh со старым token", "expected": "Status 401"},
        ],
    },
    {
        "title": "Экспорт: REST Assured генерация Java тестов",
        "description": "Проверка генерации Java тестов из сессии",
        "preconditions": "Сессия с HTTP запросами",
        "postconditions": "Скачан .java файл с REST Assured тестами",
        "priority": "Medium",
        "status": "Active",
        "automation_status": "Manual",
        "folder": "Экспорт",
        "tags": ["export", "rest-assured", "java"],
        "steps": [
            {"step": 1, "action": "Выбрать сессию", "expected": "Сессия выбрана"},
            {"step": 2, "action": "Нажать 'Generate REST Assured'", "expected": "Генерация запущена"},
            {"step": 3, "action": "Скачать файл", "expected": ".java файл"},
        ],
    },
    {
        "title": "Регистрация: Регистрация с дублирующимся username",
        "description": "Проверка обработки дубликатов при регистрации",
        "preconditions": "Username уже используется в системе",
        "postconditions": "Отображается ошибка о дубликате",
        "priority": "High",
        "status": "Active",
        "automation_status": "Automated",
        "folder": "Регистрация",
        "tags": ["registration", "negative", "validation"],
        "steps": [
            {"step": 1, "action": "Открыть страницу регистрации", "expected": "Форма регистрации"},
            {"step": 2, "action": "Ввести существующий username", "expected": "Username введён"},
            {"step": 3, "action": "Нажать 'Зарегистрироваться'", "expected": "Ошибка: username занят"},
        ],
    },
]

# Demo tasks for Kanban
DEMO_TASKS = [
    {
        "title": "Добавить OAuth авторизацию через GitHub",
        "description": "Интеграция GitHub OAuth для быстрого входа разработчиков",
        "status": "todo",
        "priority": "high",
        "labels": ["feature", "auth"],
    },
    {
        "title": "Исправить дубликаты в списке сессий",
        "description": "При быстром обновлении страницы сессии дублируются в UI",
        "status": "in_progress",
        "priority": "high",
        "labels": ["bug", "ui"],
    },
    {
        "title": "Добавить фильтрацию по дате",
        "description": "Возможность фильтровать сессии по диапазону дат",
        "status": "todo",
        "priority": "medium",
        "labels": ["feature", "ux"],
    },
    {
        "title": "Оптимизировать запросы к БД",
        "description": "Добавить индексы и пагинацию для больших объемов данных",
        "status": "done",
        "priority": "high",
        "labels": ["performance", "backend"],
    },
    {
        "title": "Написать документацию API",
        "description": "Добавить OpenAPI спецификацию и примеры использования",
        "status": "in_progress",
        "priority": "medium",
        "labels": ["docs", "api"],
    },
    {
        "title": "Добавить темную тему",
        "description": "Переключатель светлая/темная тема в настройках",
        "status": "todo",
        "priority": "low",
        "labels": ["feature", "ui"],
    },
]

# Testcase folder tree structure: {folder_name: [subfolder_names]}
DEMO_TESTCASE_FOLDERS = {
    "Авторизация": ["Позитивные", "Негативные", "JWT"],
    "Регистрация": [],
    "API": ["Sessions", "TestCases", "Auth"],
    "UI": ["Dashboard", "Settings"],
    "Экспорт": ["Postman", "pytest", "Cypress"],
    "AI": ["Анализ ошибок"],
    "Security": ["XSS", "CSRF", "AuthBypass"],
}

# Map: test case folder field → tree folder name
DEMO_TC_FOLDER_MAP = {
    "Авторизация": "Авторизация",
    "Регистрация": "Регистрация",
    "API": "API",
    "UI": "UI",
    "Экспорт": "Экспорт",
    "AI": "AI",
    "Security": "Security",
}
