"""add_article_folders

Revision ID: 02eb2a85b4b4
Revises: a1b2c3d4e5f6
Create Date: 2026-02-23 15:01:08.529014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02eb2a85b4b4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('folder_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_articles_folder_id'), 'articles', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'articles', 'article_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_folder_id'), table_name='articles')
    op.drop_column('articles', 'folder_id')
    # ### end Alembic commands ###
