"""Initial schema from existing models

Revision ID: 43fb843e4a0f
Revises: 
Create Date: 2025-12-05 01:31:29.519065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fb843e4a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('testit_url', sa.String(length=500), nullable=True))
    op.add_column('sessions', sa.Column('testit_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'testit_id')
    op.drop_column('sessions', 'testit_url')
    # ### end Alembic commands ###
