"""add testcase_folders table and folder_id to test_cases

Revision ID: e8a09aa606cf
Revises: b3c4d5e6f7a8
Create Date: 2026-02-23 21:06:01.067040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a09aa606cf'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['testcase_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', 'project_id', name='uq_testcase_folder_name_parent_project')
    )
    op.create_index(op.f('ix_testcase_folders_parent_id'), 'testcase_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_testcase_folders_project_id'), 'testcase_folders', ['project_id'], unique=False)
    op.add_column('test_cases', sa.Column('folder_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_test_cases_folder_id'), 'test_cases', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'test_cases', 'testcase_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_index(op.f('ix_test_cases_folder_id'), table_name='test_cases')
    op.drop_column('test_cases', 'folder_id')
    op.drop_index(op.f('ix_testcase_folders_project_id'), table_name='testcase_folders')
    op.drop_index(op.f('ix_testcase_folders_parent_id'), table_name='testcase_folders')
    op.drop_table('testcase_folders')
    # ### end Alembic commands ###
