"""Postman Collection generator from recorded HTTP exchanges."""

import json
import re
from urllib.parse import parse_qs, urlparse

from app.models_pydantic import (
    ExportPostmanRequest,
    ExportPostmanResponse,
    PostmanBody,
    PostmanCollection,
    PostmanEvent,
    PostmanHeader,
    PostmanInfo,
    PostmanItem,
    PostmanRequest,
    PostmanUrl,
    PostmanVariable,
    RecordedHttpExchange,
)
from app.session_analyzer import detect_variables

from .base import BaseGenerator

# Headers to exclude from Postman export (browser-specific)
EXCLUDED_HEADERS = {
    "accept-encoding",
    "accept-language",
    "cache-control",
    "connection",
    "host",
    "origin",
    "referer",
    "sec-ch-ua",
    "sec-ch-ua-mobile",
    "sec-ch-ua-platform",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "upgrade-insecure-requests",
    "user-agent",
    "cookie",
}

# URL patterns to filter out (analytics, ads, static assets)
JUNK_URL_PATTERNS = [
    r"google-analytics\.com",
    r"googletagmanager\.com",
    r"facebook\.com/tr",
    r"doubleclick\.net",
    r"hotjar\.com",
    r"segment\.io",
    r"mixpanel\.com",
    r"amplitude\.com",
    r"sentry\.io",
    r"newrelic\.com",
    r"\.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot|css)(\?|$)",
    r"/_next/static/",
    r"/static/js/",
    r"/static/css/",
    r"/favicon",
]


class PostmanGenerator(BaseGenerator):
    """Generate Postman Collection from recorded HTTP sessions."""

    def __init__(
        self,
        recorded_requests: list[RecordedHttpExchange],
        collection_name: str = "ErrorLens Collection",
        base_url_variable: bool = True,
        generate_tests: bool = True,
    ):
        super().__init__(recorded_requests)
        self.collection_name = collection_name
        self.base_url_variable = base_url_variable
        self.generate_tests = generate_tests

    def get_file_extension(self) -> str:
        return ".postman_collection.json"

    def get_language(self) -> str:
        return "json"

    def generate(self) -> str:
        """Generate Postman Collection JSON."""
        response = self.generate_collection()
        return json.dumps(response.collection.model_dump(exclude_none=True), indent=2)

    def generate_collection(self) -> ExportPostmanResponse:
        """Generate Postman Collection object."""
        # Filter out junk requests
        filtered = [ex for ex in self.requests if not self._is_junk_request(ex.request.url)]
        if not filtered:
            filtered = self.requests

        # Detect variables (tokens, IDs)
        detected_vars = detect_variables(filtered)

        # Extract base URL
        variables = []
        base_url = None
        if self.base_url_variable:
            base_url = self.base_url
            variables.append(PostmanVariable(key="baseUrl", value=base_url))

        # Add detected variables
        for var_name, var_data in detected_vars.items():
            variables.append(PostmanVariable(key=var_name, value=var_data["value"]))

        # Convert exchanges to Postman items
        items = [self._exchange_to_item(ex, base_url) for ex in filtered]

        # Add variable extraction scripts
        items = self._add_variable_extraction_scripts(items, filtered, detected_vars)

        collection = PostmanCollection(
            info=PostmanInfo(
                name=self.collection_name,
                description=f"Generated by ErrorLens from {len(items)} recorded requests. "
                f"Detected {len(detected_vars)} variables.",
            ),
            item=items,
            variable=variables,
        )

        return ExportPostmanResponse(
            collection=collection,
            requests_count=len(items),
            variables_count=len(variables),
        )

    def _is_junk_request(self, url: str) -> bool:
        """Check if URL matches junk patterns."""
        for pattern in JUNK_URL_PATTERNS:
            if re.search(pattern, url, re.IGNORECASE):
                return True
        return False

    def _filter_headers(self, headers: dict[str, str]) -> list[PostmanHeader]:
        """Filter out browser-specific headers."""
        return [
            PostmanHeader(key=k, value=v)
            for k, v in headers.items()
            if k.lower() not in EXCLUDED_HEADERS
        ]

    def _parse_url(self, url: str, base_url: str | None) -> PostmanUrl:
        """Parse URL into Postman URL structure."""
        parsed = urlparse(url)

        raw = url
        if base_url and url.startswith(base_url):
            raw = "{{baseUrl}}" + url[len(base_url) :]

        query_params = []
        if parsed.query:
            qs = parse_qs(parsed.query, keep_blank_values=True)
            for key, values in qs.items():
                for value in values:
                    query_params.append({"key": key, "value": value})

        path_segments = [seg for seg in parsed.path.split("/") if seg]

        return PostmanUrl(
            raw=raw,
            protocol=parsed.scheme or None,
            host=parsed.netloc.split(".") if parsed.netloc else None,
            path=path_segments or None,
            query=query_params or None,
        )

    def _generate_test_script(self, exchange: RecordedHttpExchange) -> PostmanEvent:
        """Generate pm.test() assertions for a request."""
        tests = []
        status = exchange.response.status

        # Status code test
        tests.append(
            f'pm.test("Status code is {status}", function () {{\n'
            f"    pm.response.to.have.status({status});\n"
            f"}});"
        )

        # Response time test
        if exchange.response.duration_ms > 0:
            threshold = max(exchange.response.duration_ms * 2, 2000)
            tests.append(
                f'pm.test("Response time is acceptable", function () {{\n'
                f"    pm.expect(pm.response.responseTime).to.be.below({threshold});\n"
                f"}});"
            )

        # JSON validation
        content_type = exchange.response.headers.get("content-type", "")
        if "application/json" in content_type.lower() and exchange.response.body:
            try:
                response_json = json.loads(exchange.response.body)
                if isinstance(response_json, dict):
                    for field in ["id", "data", "error", "errors"]:
                        if field in response_json:
                            tests.append(
                                f'pm.test("Response has {field} field", function () {{\n'
                                f"    var jsonData = pm.response.json();\n"
                                f'    pm.expect(jsonData).to.have.property("{field}");\n'
                                f"}});"
                            )
            except (json.JSONDecodeError, TypeError):
                pass

        return PostmanEvent(
            listen="test",
            script={
                "type": "text/javascript",
                "exec": "\n\n".join(tests).split("\n"),
            },
        )

    def _exchange_to_item(
        self, exchange: RecordedHttpExchange, base_url: str | None
    ) -> PostmanItem:
        """Convert a recorded HTTP exchange to Postman item."""
        parsed = urlparse(exchange.request.url)
        path = parsed.path or "/"
        name = f"{exchange.request.method} {path}"

        headers = self._filter_headers(exchange.request.headers)

        body = None
        if exchange.request.body:
            content_type = exchange.request.content_type or ""
            if "application/json" in content_type.lower():
                body = PostmanBody(
                    mode="raw",
                    raw=exchange.request.body,
                    options={"raw": {"language": "json"}},
                )
            elif "application/x-www-form-urlencoded" in content_type.lower():
                body = PostmanBody(mode="urlencoded", raw=exchange.request.body)
            else:
                body = PostmanBody(mode="raw", raw=exchange.request.body)

        url = self._parse_url(exchange.request.url, base_url)

        request = PostmanRequest(
            method=exchange.request.method,
            header=headers,
            body=body,
            url=url,
        )

        events = []
        if self.generate_tests:
            events.append(self._generate_test_script(exchange))

        return PostmanItem(
            name=name,
            event=events,
            request=request,
            response=[],
        )

    def _add_variable_extraction_scripts(
        self,
        items: list[PostmanItem],
        exchanges: list[RecordedHttpExchange],
        detected_vars: dict,
    ) -> list[PostmanItem]:
        """Add scripts to extract variables from responses."""
        id_to_index = {ex.id: i for i, ex in enumerate(exchanges)}

        for var_name, var_data in detected_vars.items():
            source_id = var_data["source_request_id"]
            if source_id not in id_to_index:
                continue

            idx = id_to_index[source_id]
            source_path = var_data["source_path"]

            if "response.body." in source_path:
                json_path = source_path.replace("response.body.", "")
                script_lines = [
                    "// Extract variable from response",
                    "var jsonData = pm.response.json();",
                    f"var value = jsonData.{json_path};",
                    "if (value) {",
                    f'    pm.collectionVariables.set("{var_name}", value);',
                    f'    console.log("Extracted {var_name}:", value);',
                    "}",
                ]
            elif "response.headers." in source_path:
                header_name = source_path.replace("response.headers.", "")
                script_lines = [
                    "// Extract variable from response header",
                    f'var value = pm.response.headers.get("{header_name}");',
                    "if (value) {",
                    f'    pm.collectionVariables.set("{var_name}", value);',
                    f'    console.log("Extracted {var_name}:", value);',
                    "}",
                ]
            else:
                continue

            existing_events = items[idx].event
            test_event = next((e for e in existing_events if e.listen == "test"), None)

            if test_event:
                existing_exec = test_event.script.get("exec", [])
                test_event.script["exec"] = script_lines + [""] + existing_exec
            else:
                items[idx].event.append(
                    PostmanEvent(
                        listen="test",
                        script={
                            "type": "text/javascript",
                            "exec": script_lines,
                        },
                    )
                )

        return items


# =============================================================================
# Public API (backward compatible)
# =============================================================================


def generate_postman_collection(request: ExportPostmanRequest) -> ExportPostmanResponse:
    """Generate Postman Collection from recorded HTTP exchanges."""
    generator = PostmanGenerator(
        recorded_requests=request.recorded_requests,
        collection_name=request.collection_name,
        base_url_variable=request.base_url_variable,
        generate_tests=request.generate_tests,
    )
    return generator.generate_collection()
